keys:
  - &personal age18qj0jec3zd08uvyqs528zns4mh4vfy9eml0h5jn8nwftp8975fdqwsfe0t
  - &work age1atqgd6gkk8652nvk6gazdpvzrp9yuk46vped2kxuqnzu7tl5s5qq3wud4t
  - &hel-1 age17ymrxestjdajl0k7lgyurtqd0dgg0kan53v38s9vkrzctm8lmpfqr4vulk
  - &picard age1ttmamy82z5d7u4k5jr3u07w3y82z0pmyhp4q387uexkjmqaut9zsj98d4z
  - &surface age1j2s4pc26w7cvq4603ml42pnev02wgzzskvc6cmqk956npmy7v4ssc32rs2
  - &lore age1n3sy82k0fqme3ffsul8eme5j428z74aadk47kejwzewt0pkleqxqv29j29
  - &worf age1a7rd5exug5qcatf3kyyqlm9dejcgrvgyf6hp0xr0gq9c9563m52sywpckf
  - &pi01 age1twx77345dcp02uf4hysxg7xu9tk6nya87mgvpjs28l4vx29emsqshf9npz
  - &pi02 age1re5axnlmdaafldlzdk8ksq8ka7pnptpwuaj5rqdc2w4p02x6wqys39fhhh
  - &pi03 age1y0gxel6tfdtxx7rl3asyzg3sqxauevgej0angu20ppqxw5uwpf7sz8mej6
  - &pi04 age164h7c8h3daax52exq9rw2lt2s92uyy8ycspygu3e5px8nv857qrqggd53e
  - &pi05 age1w4m9tt3zxkwqg204nccpc08yqd7t2pm2d7w9k3mjmh4e3x7wsg5sk7asv7
  - &tpi01 age1g26wlf79vqr7ss922p7v56jskzlwem43ec6h9tu2t965gwgw89dqwdr445
  - &tpi02 age1k5aqwr0l4vtr3728vwvvr0hvx7jr3acrygkp7fggkkym7xkfy5dqur36ug
  - &tpi03 age1uz82l53qt2y6gnplw6cuuq3mru6u883puzslf34z8sqje24rh9hstg3wjr
  - &tpi04 age1at9me34tufn6enrwjjuz4tsrudz7kjqg7rlcgdk54kmfmq22nghqztphv9
  - &uconsole age1qdmh028fh8vjsd44uh5m9ml7c54v4nwl77mrwv3tugyzgym7wf3sae2q8r
  - &lwh-hotapril age1jkpl02yqka2a66duvm752cn7307cel0sndk9salqy6vmhj2vve4ssr2kn6
creation_rules:
  - path_regex: ^nix\/secrets\/(personal|turing).(yaml|json|env|ini)$
    key_groups:
    - age:
      - *personal
  - path_regex: ^nix\/secrets\/work.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *work
  - path_regex: ^nix\/hosts\/secrets.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *personal
      - *hel-1
      - *picard
      - *surface
      - *lore
      - *worf
      - *pi01
      - *pi02
      - *pi03
      - *pi04
      - *pi05
      - *tpi01
      - *tpi02
      - *tpi03
      - *tpi04
      - *uconsole
      - *lwh-hotapril
# nix-shell -p ssh-to-age --run 'ssh-keyscan pi01.lan | ssh-to-age'
# export SOPS_AGE_KEY_FILE=~/.config/sops/age/keys.txt
# nix-shell -p sops --run "sops updatekeys nix/hosts/secrets.yaml"
