keys:
  - &personal age18qj0jec3zd08uvyqs528zns4mh4vfy9eml0h5jn8nwftp8975fdqwsfe0t
  - &heanet age1atqgd6gkk8652nvk6gazdpvzrp9yuk46vped2kxuqnzu7tl5s5qq3wud4t
  - &hel-1 age17ymrxestjdajl0k7lgyurtqd0dgg0kan53v38s9vkrzctm8lmpfqr4vulk
  - &picard age17leaj82hje5y6ckpsuhkfk0rjk9wpyf62wdezh7pls32vmhlayestdz0y7
  - &surface age1j2s4pc26w7cvq4603ml42pnev02wgzzskvc6cmqk956npmy7v4ssc32rs2
  - &lore age1n3sy82k0fqme3ffsul8eme5j428z74aadk47kejwzewt0pkleqxqv29j29
  - &worf age1a7rd5exug5qcatf3kyyqlm9dejcgrvgyf6hp0xr0gq9c9563m52sywpckf
  - &pi01 age1fm8jf6jpczhp7lv6feda0k5ktnvuq7gkr7qyc2c4yv663xcqhpwqg6mt7n
creation_rules:
  - path_regex: ^nix\/secrets\/(personal|turing).(yaml|json|env|ini)$
    key_groups:
    - age:
      - *personal
  - path_regex: ^nix\/secrets\/heanet.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *heanet
  - path_regex: ^nix\/hosts\/secrets.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *personal
      - *hel-1
      - *picard
      - *surface
      - *lore
      - *worf
      - *pi01
# ssh-to-age --run 'ssh-keyscan pi01.lan | ssh-to-age'
# export SOPS_AGE_KEY_FILE=~/.config/sops/age/keys.txt
# nix-shell -p sops --run "sops updatekeys nix/hosts/secrets.yaml"
