keys:
  - &personal age18qj0jec3zd08uvyqs528zns4mh4vfy9eml0h5jn8nwftp8975fdqwsfe0t
  - &heanet age1atqgd6gkk8652nvk6gazdpvzrp9yuk46vped2kxuqnzu7tl5s5qq3wud4t
  - &hel-1 age17ymrxestjdajl0k7lgyurtqd0dgg0kan53v38s9vkrzctm8lmpfqr4vulk
  - &picard age17leaj82hje5y6ckpsuhkfk0rjk9wpyf62wdezh7pls32vmhlayestdz0y7
  - &surface age1j2s4pc26w7cvq4603ml42pnev02wgzzskvc6cmqk956npmy7v4ssc32rs2
creation_rules:
  - path_regex: modules/home-manager/personas/secrets/(personal|turing).(yaml|json|env|ini)$
    key_groups:
    - age:
      - *personal
  - path_regex: modules/home-manager/personas/secrets/heanet.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *heanet
  - path_regex: nixos/hosts/secrets.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *personal
      - *hel-1
      - *picard
      - *surface